[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ferrox-py-utils"
version = "1.0.1"
description = "Data Engineering and ETL utilities for the Ferrox ecosystem."
authors = [{ name = "AI-Autistic-Intelligence" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ferrox-py>=1.0.0",
    "pydantic>=2.0"
]
